import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { projectService } from '../services/projectService';
import { ArrowLeft, Download, FileCode, Check, Copy } from 'lucide-react';
import Loader from '../components/common/Loader';
import MermaidRenderer from '../components/report/MermaidRenderer';

/**
 * Detailed report page containing navigation tabs for the 19 architecture sections.
 */
const ReportPage = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [project, setProject] = useState(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState('projectOverview');
  const [copied, setCopied] = useState(false);
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    fetchProject();
  }, [id]);

  const fetchProject = async () => {
    try {
      setLoading(true);
      const data = await projectService.getProjectById(id);
      setProject(data);
    } catch (err) {
      console.error(err);
      navigate('/');
    } finally {
      setLoading(false);
    }
  };

  const handleExport = async (format) => {
    try {
      setExporting(true);
      await projectService.downloadExport(id, format);
    } catch (err) {
      alert('Export failed.');
    } finally {
      setExporting(false);
    }
  };

  const handleCopy = (text) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (loading) {
    return <Loader message="Compiling architecture blueprint pages..." />;
  }

  const report = project?.architectureReport || {};

  // Defining the tabs mapping to the 19 columns
  const tabs = [
    { key: 'projectOverview', label: 'Overview' },
    { key: 'businessRequirements', label: 'Business Req' },
    { key: 'functionalRequirements', label: 'Functional Req' },
    { key: 'nonFunctionalRequirements', label: 'Non-Functional' },
    { key: 'modules', label: 'Modules' },
    { key: 'databaseDesign', label: 'Database Design' },
    { key: 'sqlStatements', label: 'SQL Statements' },
    { key: 'erDiagramMermaid', label: 'ER Diagram' },
    { key: 'apiEndpoints', label: 'API Endpoints' },
    { key: 'springBootStructure', label: 'Spring Structure' },
    { key: 'jpaEntities', label: 'JPA Entities' },
    { key: 'dtoClasses', label: 'DTO Classes' },
    { key: 'validationRules', label: 'Validation Rules' },
    { key: 'securityRecommendations', label: 'Security' },
    { key: 'rbacDesign', label: 'RBAC' },
    { key: 'passwordStrategy', label: 'Password Policy' },
    { key: 'microservicesRecommendation', label: 'Microservices' },
    { key: 'deploymentStrategy', label: 'Deployment' },
    { key: 'developmentRoadmap', label: 'Roadmap' }
  ];

  const activeContent = report[activeTab] || 'Section empty or not generated by AI.';

  return (
    <div style={{ maxWidth: '1400px', margin: '0 auto', padding: '0 20px 40px' }}>
      
      {/* Top Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', margin: '30px 0 20px' }}>
        <button 
          onClick={() => navigate('/')} 
          style={{ display: 'flex', alignItems: 'center', gap: '6px', background: 'transparent', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer', fontSize: '0.9rem', transition: 'var(--transition)' }}
          onMouseEnter={e => e.currentTarget.style.color = 'var(--text-primary)'}
          onMouseLeave={e => e.currentTarget.style.color = 'var(--text-secondary)'}
        >
          <ArrowLeft size={16} />
          <span>Dashboard</span>
        </button>

        {/* Exporters Dropdown */}
        <div style={{ display: 'flex', gap: '10px' }}>
          <button onClick={() => handleExport('markdown')} className="btn-primary" style={{ padding: '8px 14px', background: 'transparent', border: '1px solid var(--border-color)', boxShadow: 'none', borderRadius: '8px', fontSize: '0.85rem' }}>
            <Download size={14} />
            <span>Markdown</span>
          </button>
          <button onClick={() => handleExport('json')} className="btn-primary" style={{ padding: '8px 14px', background: 'transparent', border: '1px solid var(--border-color)', boxShadow: 'none', borderRadius: '8px', fontSize: '0.85rem' }}>
            <Download size={14} />
            <span>JSON</span>
          </button>
          <button onClick={() => handleExport('pdf')} className="btn-primary" style={{ padding: '8px 14px', borderRadius: '8px', fontSize: '0.85rem' }}>
            <Download size={14} />
            <span>PDF</span>
          </button>
        </div>
      </div>

      <div style={{ marginBottom: '30px' }}>
        <h1 style={{ fontSize: '1.85rem', fontWeight: '800', marginBottom: '6px' }}>{project?.title}</h1>
        <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>Project ID: {project?.id} &bull; Generated using Gemini 2.0 Flash</p>
      </div>

      {/* Main Container Grid */}
      <div style={{ display: 'grid', gridTemplateColumns: '280px 1fr', gap: '30px', alignItems: 'start' }}>
        
        {/* Sidebar Menu */}
        <div className="glass-panel" style={{ padding: '15px', borderRadius: '16px', display: 'flex', flexDirection: 'column', gap: '6px', maxHeight: '75vh', overflowY: 'auto' }}>
          {tabs.map((tab) => (
            <button
              key={tab.key}
              onClick={() => setActiveTab(tab.key)}
              style={{
                width: '100%',
                textAlign: 'left',
                padding: '10px 15px',
                border: 'none',
                borderRadius: '8px',
                background: activeTab === tab.key ? 'var(--primary-gradient)' : 'transparent',
                color: activeTab === tab.key ? 'white' : 'var(--text-secondary)',
                fontWeight: activeTab === tab.key ? '700' : '400',
                cursor: 'pointer',
                fontSize: '0.85rem',
                transition: 'var(--transition)'
              }}
              onMouseEnter={e => {
                if (activeTab !== tab.key) e.currentTarget.style.background = 'rgba(255, 255, 255, 0.03)';
              }}
              onMouseLeave={e => {
                if (activeTab !== tab.key) e.currentTarget.style.background = 'transparent';
              }}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {/* Content Viewer */}
        <div className="glass-panel" style={{ padding: '40px', borderRadius: '20px', minHeight: '600px', display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
          <div>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid var(--border-color)', paddingBottom: '15px', marginBottom: '25px' }}>
              <h2 style={{ fontSize: '1.4rem', fontWeight: '800' }}>{tabs.find(t => t.key === activeTab)?.label}</h2>
              <button 
                onClick={() => handleCopy(activeContent)}
                style={{ background: 'transparent', border: '1px solid var(--border-color)', cursor: 'pointer', padding: '6px 12px', borderRadius: '8px', color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', gap: '6px', fontSize: '0.8rem', transition: 'var(--transition)' }}
              >
                {copied ? <Check size={14} color="var(--success)" /> : <Copy size={14} />}
                <span>{copied ? 'Copied!' : 'Copy Code'}</span>
              </button>
            </div>

            {/* Special Rendering for ER Diagrams */}
            {activeTab === 'erDiagramMermaid' ? (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
                <MermaidRenderer chart={activeContent} />
                <pre style={{ overflowX: 'auto', background: '#090d16', padding: '15px', borderRadius: '8px', border: '1px solid var(--border-color)', fontSize: '0.8rem', color: 'var(--text-secondary)' }}>{activeContent}</pre>
              </div>
            ) : (
              // General markdown block rendering representation
              <div style={{ whiteSpace: 'pre-wrap', lineHeight: '1.7', fontSize: '0.95rem', color: 'var(--text-secondary)', fontFamily: activeTab.match(/sql|entities|dto|structure/) ? 'Courier New, Courier, monospace' : 'inherit' }}>
                {activeContent}
              </div>
            )}
          </div>
        </div>

      </div>
    </div>
  );
};

export default ReportPage;
