package com.aiarchitect.service;

import com.aiarchitect.dto.response.ArchitectureReportResponse;
import com.aiarchitect.exception.ResourceNotFoundException;
import com.aiarchitect.exception.UnauthorizedException;
import com.aiarchitect.model.ArchitectureReport;
import com.aiarchitect.model.ExportHistory;
import com.aiarchitect.model.Project;
import com.aiarchitect.repository.ExportHistoryRepository;
import com.aiarchitect.repository.ProjectRepository;
import com.aiarchitect.util.AppConstants;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;

/**
 * Service class handling project export formatting (PDF, Markdown, JSON) and audit trails.
 *
 * Implements:
 * 1. Ownership enforcement (users can only download their own projects).
 * 2. Pretty-printing JSON of the report fields.
 * 3. Assembling custom Markdown documents.
 * 4. PDF rendering flow via OpenPDF.
 * 5. Writing export records into `export_history` database table on each download.
 */
@Service
@Slf4j
@RequiredArgsConstructor
public class ExportService {

    private final ProjectRepository projectRepository;
    private final ExportHistoryRepository exportHistoryRepository;
    private final ObjectMapper objectMapper;

    /**
     * Formats the project's architecture report as a markdown document.
     */
    @Transactional
    public String exportToMarkdown(Long projectId, String userEmail) {
        log.info("Request to export project ID {} to Markdown by user {}", projectId, userEmail);

        Project project = getProjectAndValidate(projectId, userEmail);
        ArchitectureReport report = project.getArchitectureReport();
        if (report == null) {
            throw new ResourceNotFoundException("ArchitectureReport", "projectId", projectId);
        }

        StringBuilder sb = new StringBuilder();
        sb.append("# ").append(project.getTitle()).append("\n\n");
        sb.append("> Generated by AI Software Architect on ").append(project.getCreatedAt()).append("\n\n");

        addMdSection(sb, "Project Overview", report.getProjectOverview());
        addMdSection(sb, "Business Requirements", report.getBusinessRequirements());
        addMdSection(sb, "Functional Requirements", report.getFunctionalRequirements());
        addMdSection(sb, "Non-Functional Requirements", report.getNonFunctionalRequirements());
        addMdSection(sb, "System Modules", report.getModules());
        addMdSection(sb, "Database Design", report.getDatabaseDesign());
        addMdSection(sb, "SQL Statements", report.getSqlStatements());
        addMdSection(sb, "ER Diagram (Mermaid)", report.getErDiagramMermaid());
        addMdSection(sb, "API Endpoints", report.getApiEndpoints());
        addMdSection(sb, "Spring Boot Package Structure", report.getSpringBootStructure());
        addMdSection(sb, "JPA Entities", report.getJpaEntities());
        addMdSection(sb, "DTO Classes", report.getDtoClasses());
        addMdSection(sb, "Validation Rules", report.getValidationRules());
        addMdSection(sb, "Security Recommendations", report.getSecurityRecommendations());
        addMdSection(sb, "RBAC Design", report.getRbacDesign());
        addMdSection(sb, "Password Strategy", report.getPasswordStrategy());
        addMdSection(sb, "Microservices Recommendation", report.getMicroservicesRecommendation());
        addMdSection(sb, "Deployment Strategy", report.getDeploymentStrategy());
        addMdSection(sb, "Development Roadmap", report.getDevelopmentRoadmap());

        saveExportHistory(project, AppConstants.EXPORT_FORMAT_MARKDOWN);

        return sb.toString();
    }

    /**
     * Serializes the project's architecture report as pretty-printed JSON.
     */
    @Transactional
    public String exportToJson(Long projectId, String userEmail) {
        log.info("Request to export project ID {} to JSON by user {}", projectId, userEmail);

        Project project = getProjectAndValidate(projectId, userEmail);
        ArchitectureReport report = project.getArchitectureReport();
        if (report == null) {
            throw new ResourceNotFoundException("ArchitectureReport", "projectId", projectId);
        }

        try {
            saveExportHistory(project, AppConstants.EXPORT_FORMAT_JSON);

            // Map to flat Response DTO first to avoid circular reference loops on entities
            ArchitectureReportResponse dto = convertToReportResponse(report);
            return objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(dto);
        } catch (Exception e) {
            log.error("Failed to serialize report to JSON for project ID {}", projectId, e);
            throw new RuntimeException("Could not serialize report to JSON", e);
        }
    }

    /**
     * Generates a stylized PDF document using OpenPDF and returns raw binary bytes.
     */
    @Transactional
    public byte[] exportToPdf(Long projectId, String userEmail) {
        log.info("Request to export project ID {} to PDF by user {}", projectId, userEmail);

        Project project = getProjectAndValidate(projectId, userEmail);
        ArchitectureReport report = project.getArchitectureReport();
        if (report == null) {
            throw new ResourceNotFoundException("ArchitectureReport", "projectId", projectId);
        }

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Document document = new Document(PageSize.A4, 50, 50, 50, 50);

        try {
            PdfWriter.getInstance(document, out);
            document.open();

            // Cover Title Section
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22);
            Paragraph title = new Paragraph(project.getTitle(), titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(10);
            document.add(title);

            Font subFont = FontFactory.getFont(FontFactory.HELVETICA, 11);
            Paragraph metadata = new Paragraph("Generated by AI Software Architect\nDate: " + LocalDateTime.now(), subFont);
            metadata.setAlignment(Element.ALIGN_CENTER);
            metadata.setSpacingAfter(30);
            document.add(metadata);

            // Report Sections
            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14);
            Font bodyFont = FontFactory.getFont(FontFactory.HELVETICA, 10);

            addPdfSection(document, "1. Project Overview", report.getProjectOverview(), headerFont, bodyFont);
            addPdfSection(document, "2. Business Requirements", report.getBusinessRequirements(), headerFont, bodyFont);
            addPdfSection(document, "3. Functional Requirements", report.getFunctionalRequirements(), headerFont, bodyFont);
            addPdfSection(document, "4. Non-Functional Requirements", report.getNonFunctionalRequirements(), headerFont, bodyFont);
            addPdfSection(document, "5. System Modules", report.getModules(), headerFont, bodyFont);
            addPdfSection(document, "6. Database Design", report.getDatabaseDesign(), headerFont, bodyFont);
            addPdfSection(document, "7. SQL Statements", report.getSqlStatements(), headerFont, bodyFont);
            addPdfSection(document, "8. API Endpoints", report.getApiEndpoints(), headerFont, bodyFont);
            addPdfSection(document, "9. Spring Boot Package Structure", report.getSpringBootStructure(), headerFont, bodyFont);
            addPdfSection(document, "10. JPA Entities", report.getJpaEntities(), headerFont, bodyFont);
            addPdfSection(document, "11. DTO Classes", report.getDtoClasses(), headerFont, bodyFont);
            addPdfSection(document, "12. Validation Rules", report.getValidationRules(), headerFont, bodyFont);
            addPdfSection(document, "13. Security Recommendations", report.getSecurityRecommendations(), headerFont, bodyFont);
            addPdfSection(document, "14. RBAC Design", report.getRbacDesign(), headerFont, bodyFont);
            addPdfSection(document, "15. Password Strategy", report.getPasswordStrategy(), headerFont, bodyFont);
            addPdfSection(document, "16. Microservices Recommendation", report.getMicroservicesRecommendation(), headerFont, bodyFont);
            addPdfSection(document, "17. Deployment Strategy", report.getDeploymentStrategy(), headerFont, bodyFont);
            addPdfSection(document, "18. Development Roadmap", report.getDevelopmentRoadmap(), headerFont, bodyFont);

            document.close();

            saveExportHistory(project, AppConstants.EXPORT_FORMAT_PDF);

            return out.toByteArray();

        } catch (Exception e) {
            log.error("Failed to construct PDF document bytes: {}", e.getMessage(), e);
            throw new RuntimeException("Error rendering PDF report", e);
        }
    }

    // ---- Helper Methods ----

    private Project getProjectAndValidate(Long id, String email) {
        Project project = projectRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Project", "id", id));

        if (!project.getUser().getEmail().equals(email)) {
            log.warn("Unauthorized export attempt by user {} on project ID {}", email, id);
            throw new UnauthorizedException("You are not authorized to export this project");
        }
        return project;
    }

    private void saveExportHistory(Project project, String format) {
        ExportHistory history = ExportHistory.builder()
                .project(project)
                .format(format)
                .build();
        exportHistoryRepository.save(history);
    }

    private void addMdSection(StringBuilder sb, String title, String content) {
        if (content == null || content.isBlank()) {
            return;
        }
        sb.append("## ").append(title).append("\n\n");
        if (title.contains("Mermaid")) {
            sb.append("```mermaid\n").append(content.trim()).append("\n```\n\n");
        } else {
            sb.append(content.trim()).append("\n\n");
        }
    }

    private void addPdfSection(Document document, String title, String content, Font headerFont, Font bodyFont) throws Exception {
        if (content == null || content.isBlank()) {
            return;
        }
        Paragraph header = new Paragraph(title, headerFont);
        header.setSpacingBefore(12);
        header.setSpacingAfter(4);
        document.add(header);

        Paragraph body = new Paragraph(content, bodyFont);
        body.setSpacingAfter(12);
        document.add(body);
    }

    private ArchitectureReportResponse convertToReportResponse(ArchitectureReport report) {
        return ArchitectureReportResponse.builder()
                .id(report.getId())
                .projectOverview(report.getProjectOverview())
                .businessRequirements(report.getBusinessRequirements())
                .functionalRequirements(report.getFunctionalRequirements())
                .nonFunctionalRequirements(report.getNonFunctionalRequirements())
                .modules(report.getModules())
                .databaseDesign(report.getDatabaseDesign())
                .sqlStatements(report.getSqlStatements())
                .erDiagramMermaid(report.getErDiagramMermaid())
                .apiEndpoints(report.getApiEndpoints())
                .springBootStructure(report.getSpringBootStructure())
                .jpaEntities(report.getJpaEntities())
                .dtoClasses(report.getDtoClasses())
                .validationRules(report.getValidationRules())
                .securityRecommendations(report.getSecurityRecommendations())
                .rbacDesign(report.getRbacDesign())
                .passwordStrategy(report.getPasswordStrategy())
                .microservicesRecommendation(report.getMicroservicesRecommendation())
                .deploymentStrategy(report.getDeploymentStrategy())
                .developmentRoadmap(report.getDevelopmentRoadmap())
                .createdAt(report.getCreatedAt())
                .build();
    }
}
